config/routes.rb
ProfilesDialog::Application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    mount HudsonBase::Engine, :at  => 'hudson_base', :as => 'hudson_base'

    match 'forgot_my_password' => 'user#forgot_my_password', as: :forgot_password, via: :all
    match 'locations' => 'locations#index', as: :locations, via: :all
    match 'login' => 'user#login', as: :login, via: :all
    match 'logout' => 'user#logout', as: :logout, via: :all
    match 'new' => 'profile#new', as: :new, via: :all
    match 'points' => 'points#index', as: :points, via: :all
    # match 'points_clone' => 'points#index_clone', as: :points_clone, via: :all
    match 'contacts' => 'contacts#index', as: :contacts, via: :get


    match 'reservations' => 'reservations#index', as: :reservations, via: :all
    get 'reservation' => 'reservations#reservation', as: :reservation
    match 'reservation/grid_info' => 'reservations#grid_info', as: :grid_info, via: :all
    get 'reservation/res_edit_address' => 'reservations#res_edit_address',
         as: :get_res_edit_address

    match 'profile' => 'profile#profile', as: :profile, via: :all
    get 'address_lookup' => 'locations#address_lookup'
    get 'location_info' => 'locations#location_info'
    get 'address_from_lookup' => 'locations#address_from_lookup'
    get "contacts/new" => 'contacts#new'
    get 'contacts/:id/edit' => 'contacts#edit', as: :contact
    post 'contacts/:id/delete' => 'contacts#delete', as: :delete_contact
    post 'contacts/:id' => 'contacts#save' , as: :update_contact
    post 'contacts' => 'contacts#create' , as: :create_contact

    post 'pud' => 'locations#pud'
    match ':action' => 'profile#index', via: :all
    match ':controller/:action' => '#index', via: :all

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.find(@site_id, current_profile.ID)
  end

  def edit
    @contacts = Contact.find(@site_id, current_profile.ID, :ID => params[:id]).first
  end

  def save
    @contacts = Contact.find(@site_id, current_profile.ID, :ID => params[:id]).first
    params[:contact].each do |key, value|
      @contacts.send("#{key}=", value)
    end
    if @contacts.save
      redirect_to @contacts
      flash[:save_message] = token('CONTACT_CAP_SAVE_MESSAGE').html_safe
    else
      redirect_to :back
      flash[:error_fields] = @contacts.error_fields
      flash[:error]        = @contacts.save_errors
    end
  rescue WebService::ServiceError => e
    send_exception_report(e)
    @errors = ['We were unable to create your contact due to a system error.']
    redirect_to :back

    flash[:error]        = @errors

  rescue Exception => e
    flash[:error] = token('CONTACT_CAP_ERROR_MESSAGE').html_safe
    raise
  end

  def new
    @contacts = Contact.new(@site_id, current_profile.ID)
  end

  def delete
    @contact = Contact.find(@site_id, current_profile.ID, ID: params[:id]).first
    flash[:save_message] = 'The contact was deleted.' if @contact.try(:delete)
    redirect_to @contact

  rescue StandardError
    flash[:error] = 'The contact could not be deleted due to a system error.'
    redirect_to contacts_url
  end

  def create
    if @site_id.blank?
      redirect_to(login_url) and return
    end
    @contacts = Contact.new(@site_id, current_profile.ID)
    params[:contact].each do |key, value|
      @contacts.send("#{key}=", value)
    end
    if @contacts.save
      redirect_to @contacts
      flash[:save_message] = token('CONTACT_CAP_SAVE_MESSAGE').html_safe
    else
      redirect_to :back
      flash[:error_fields] = @contacts.error_fields
      flash[:error]        = @contacts.save_errors
    end
  rescue WebService::ServiceError => e
    send_exception_report(e)
    @errors = ['We were unable to create your contact due to a system error.']
    redirect_to :back
    flash[:error]        = @errors

  rescue Exception => e
    flash[:error] = token('CONTACT_CAP_ERROR_MESSAGE').html_safe
    raise
  end


  private
  def contact_email_locked?
    unless @contacts.new_record?
      locked = token('CONTACT_LOCK_EMAIL')
      locked.to_i == 1
    end
  end
  helper_method :contact_email_locked?
end

app/helpers/contact_helper.rb
module ContactHelper

  def contact_error(contact, field)
    (flash[:error_fields] && flash[:error_fields].include?(field)) ?
        'field_error' : ''
  end

  def contact_name_label
    token('CONTACT_CAP_NAME').html_safe
  end

  def contact_address_label
    token('CONTACT_CAP_ADDRESS').html_safe
  end

  def contact_email_label
    token('CONTACT_CAP_EMAIL').html_safe
  end

  def contact_city_label
    token('CONTACT_CAP_CITY').html_safe
  end

  def contact_state_label
    token('CONTACT_CAP_STATE').html_safe
  end

  def contact_zip_label
    token('CONTACT_CAP_ZIP').html_safe
  end

  def contact_telephone_label
    token('CONTACT_CAP_TELEPHONE').html_safe
  end

  def contact_comments_label
    token('CONTACT_CAP_COMMENTS').html_safe
  end

  def contact_authorized_label
    token('CONTACT_CAP_AUTHORIZED').html_safe
  end

  def contact_contact_type_label
    token('CONTACT_CAP_CONTACT_TYPE').html_safe
  end

  def contact_alt_telephone_label
    token('CONTACT_CAP_ALT_TELEPHONE').html_safe
  end

  # def contact_personal_header
  #   token('CONTACT_CAP_SECT_PERSONAL').html_safe
  #     if token('CONTACT_CAP_SECT_PERSONAL').blank?
  #       contact_personal_header = 'Contact Personal Information'
  #     end
  # end

  def successful_save_message
    token('CONTACT_CAP_SAVE_MESSAGE').html_safe
  end

  def contact_index_header
    token_value = token('CONTACT_CAP_INDEX_HEADER').html_safe
    token_value = "Contacts" if token_value.blank?
    token_value
  end

  def contact_personal_header
    token_value = token('CONTACT_CAP_SECT_PERSONAL').html_safe
    token_value = "Contact Personal Information" if token_value.blank?
    token_value
  end

  def contact_address_header
    token_value = token('CONTACT_CAP_SECT_ADDRESS').html_safe
    token_value = "Address" if token_value.blank?
    token_value
  end

  def contact_detail_header
    token_value = token('CONTACT_CAP_SECT_DETAIL').html_safe
    token_value = "Details" if token_value.blank?
    token_value
  end

  def contact_comments_header
    token_value = token('CONTACT_CAP_SECT_COMMENT').html_safe
    token_value = "Comments" if token_value.blank?
    token_value
  end

  def no_contact_present_message
    token('CONTACT_CAP_NO_CONTACTS').html_safe
  end

  def create_button_label
    token('CONTACT_CAP_CREATE_BUTTON').html_safe
  end

  def update_button_label
    token('CONTACT_CAP_UPDATE_BUTTON').html_safe
  end

  def name_label
    token('CONTACT_CAP_NAME').html_safe
  end

  def title_label
    token('CONTACT_CAP_TITLE').html_safe
  end

  def email_label
    token('CONTACT_CAP_EMAIL').html_safe
  end

  def telephone_label
    token('CONTACT_CAP_TELEPHONE').html_safe
  end

  def alt_telephone_label
    token('CONTACT_CAP_ALT_TELEPHONE').html_safe
  end

  def contact_fax_label
    token('CONTACT_CAP_CONTACT_FAX').html_safe
  end

  def comment_label
    token('CONTACT_CAP_COMMENTS').html_safe
  end

  def contact_country_label
    token('CONTACT_CAP_COUNTRY').html_safe
  end

  def address_label
    token('CONTACT_CAP_ADDRESS').html_safe
  end

  def city_label
    token('CONTACT_CAP_CITY').html_safe
  end

  def state_label
    token('CONTACT_CAP_STATE').html_safe
  end

  def zip_code_label
    token('CONTACT_CAP_ZIP_CODE').html_safe
  end

  def contact_type_label
    token_value = token('CONTACT_CAP_CONTACT_TYPE').html_safe
    token_value = "Contact Type" if token_value.blank?
    token_value
  end

  def authorized_label
    token('CONTACT_CAP_AUTHORIZED').html_safe
  end

  def use_usphone_format?
    token('VALIDATEPHONE').to_i == 1
  end

  def contact_types_token
    token('CONTACT_TYPES')
  end


  def display_name?
    !name_label.blank?
  end

  def display_title?
    !title_label.blank?
  end

  def display_email?
    !email_label.blank?
  end

  def display_telephone?
    !telephone_label.blank?
  end

  def display_alt_telephone?
    !alt_telephone_label.blank?
  end

  def display_contact_fax?
    !contact_fax_label.blank?
  end

  def display_comment?
    !comment_label.blank?
  end

  def display_address?
    !address_label.blank?
  end

  def display_contact_country?
    !contact_country_label.blank?
  end

  def display_city?
    !city_label.blank?
  end

  def display_state?
    !state_label.blank?
  end

  def display_zip_code?
    !zip_code_label.blank?
  end

  def display_contact_type?
    !contact_type_label.blank?
  end

  def display_authorized?
    !authorized_label.blank?
  end

  def contact_types?
    !token('CONTACT_TYPES').blank?
  end

  def display_personal_section?
    display_name? || display_email? || display_telephone? || display_alt_telephone?
  end

  def display_comment_section?
    display_comment?
  end

  def display_address_section?
    display_address? || display_city? || display_state? || display_zip_code?
  end

  def display_details_section?
    display_contact_type? || display_authorized?
  end

  def display_add_contact_button?
    @profile.MaxContacts.to_i == 0 || @contacts.count < @profile.MaxContacts.to_i
  end

  def contact_type_select?
    @contacts.new_record?
  end

  def formatted_phone(phone_in)
    use_usphone_format? ? phone_in.to_s.format_phone : phone_in
    if use_usphone_format?
    else

    end
  end

end

app/views/contacts/_contacts.html.erb
<div class="yui-g" id="profile_form">
  <div class="yui-u first">
    <% if display_personal_section? %>
        <div class="content_box" id="personal_container">
          <h1 class="boxed"><%= contact_personal_header %></h1>

          <div class="contact_content">
            <ul class="form_fields">
              <% if display_name? %>
                  <li>
                    <div class="full">
                      <label><%= name_label %></label>
                    </div>
                  </li>
                  <li>
                    <div class="full contact_form">
                      <%= f.text_field :name, :class => "text #{ contact_error(@contacts, 'Name')}", :size => 35 %>
                    </div>
                  </li>
              <% end %>
              <% if display_title? %>
                  <li>
                    <div class="full">
                      <label><%= title_label %></label>
                    </div>
                  </li>

                  <li>
                    <div class="full contact_form">
                      <%= f.text_field :title, :class => "text #{ contact_error(@contacts, 'Title')}", :size => 35 %>
                    </div>
                  </li>
              <% end %>
              <% if display_email? %>
                  <li>
                    <div class="full">
                      <label><%= email_label %></label>
                    </div>
                  </li>
                  <li>
                  <li>
                    <div class="full contact_form">
                      <%= f.text_field :email_address,
                                       class:    "text #{ contact_error(@contacts, 'EmailAddress')}",
                                       size:     35,
                                       disabled: contact_email_locked? %>
                    </div>
                  </li>
              <% end %>

              <li>
                <div class="inline_block">
                  <% if display_telephone? %>
                      <div class="left_block" id="left_block_phone">
                        <div class="left">
                          <label><%= telephone_label %></label>
                        </div>

                        <div class="left contact_form">
                          <%= f.text_field :telephone, :class => "text #{ contact_error(@contacts, 'Telephone')}", :size => 25, :maxlength => 20, :value => formatted_phone(@contacts.telephone) %>
                        </div>
                      </div>
                  <% end %>
                  <div class="right_block">
                    <% if display_alt_telephone? %>
                        <div class="right">
                          <label><%= alt_telephone_label %></label>
                        </div>
                        <div class="right contact_form">
                          <%= f.text_field :telephone2, :class => "text #{ contact_error(@contacts, 'Telephone2')}", :size => 25, :maxlength => 20, :value => formatted_phone(@contacts.telephone2) %>
                        </div>
                    <% end %>
                  </div>
                  <% if display_contact_fax? %>
                      <div class="left_block" id="left_block_phone">
                        <div class="left">
                          <label><%= contact_fax_label %></label>
                        </div>

                        <div class="left contact_form">
                          <%= f.text_field :fax_number, :class => "text #{ contact_error(@contacts, 'FaxNumber')}", :size => 25, :maxlength => 20, :value => formatted_phone(@contacts.fax_number) %>
                        </div>
                      </div>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </div>
    <% end %>


    <% if display_comment_section? %>
        <div class="content_box" id="comments_container">
          <h1 class="boxed"><%= contact_comments_header %></h1>

          <div class="contact_content">
            <ul class="form_fields">
              <% if display_comment? %>
                  <li>
                    <div class="full">
                      <label><%= comment_label %></label>
                      <%= f.text_area :comments, :size => "30x30" %>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
  </div>


  <div class="yui-u">
    <% if display_address_section? %>
        <div class="content_box" id="address_container">
          <h1 class="boxed"><%= contact_address_header %></h1>

          <div class="contact_content">
            <ul class="form_fields">
              <% if display_address? %>
                  <li>
                    <div class="full">
                      <label><%= address_label %></label>
                    </div>
                  </li>
                  <li>
                    <div class="full contact_form">
                      <%= f.text_field :address, :size => 35 %>
                    </div>
                  </li>
              <% end %>
              <li>
                <div class="inline_block">
                  <% if display_city? %>
                      <div class="left_block" id="left_block_city">
                        <div class="left">
                          <label><%= city_label %></label>
                        </div>

                        <div class="left contact_form">
                          <%= f.text_field :city, :size => 15 %>
                        </div>
                      </div>
                  <% end %>
                  <% if display_state? %>
                      <div class="right_block">
                        <div class="right">
                          <label><%= state_label %></label>
                        </div>
                        <div class="right contact_form">
                          <%= f.text_field :state, :size => 5 %>
                        </div>
                      </div>
                  <% end %>
                </div>
              </li>
              <% if display_zip_code? %>
                  <li>
                    <div class="full">
                      <label><%= zip_code_label %></label>
                    </div>
                  </li>

                  <li>
                    <div class="full contact_form">
                      <%= f.text_field :zip_code, :class => "text", :size => 20 %>
                    </div>
                  </li>
              <% end %>
              <% if display_contact_country? %>
                  <li>
                    <div class="full">
                      <label><%= contact_country_label %></label>
                    </div>
                  </li>
                  <li>
                    <div class="full contact_form">
                      <%= f.country_select(:country, :include_blank => 'Please choose...',
                                           :priority_countries      => ['US', 'CA', 'MX', 'GB', 'FR'],
                                           :selected                => @contacts.country) %>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <!--This section is currently hidden-->
    <% if display_details_section? %>
        <div class="content_box" id="details_container">
          <h1 class="boxed"><%= contact_detail_header %></h1>

          <div class="contact_content">
            <ul class="form_fields">
              <li>
                <div class="inline_block">
                  <% if display_authorized? %>
                      <div class="left_block" id="left_block_auth">
                        <div class="left">
                          <label><%= authorized_label %></label>
                        </div>
                        <div class="left contact_form">
                          <%= f.check_box :authorized, {}, "1", "0" %>
                          <%#= f.check_box :authorized, {}, "true", "false" %>
                          <%#= f.check_box(:authorized, options = {}, checked_value = "1", unchecked_value = "0") %>

                        </div>
                      </div>
                  <% end %>
                  <% if display_contact_type? %>
                      <div class="right_block">
                        <div class="right">
                          <% if contact_type_select? %>
                              <label><%= contact_type_label %></label>
                          <% end %>
                        </div>
                        <div class="right contact_form">
                          <% if contact_type_select? %>
                              <%= f.select :contact_type, @contacts.contact_types%>
                          <% end %>
                          <% unless contact_type_select? %>
                              <%= f.hidden_field :contact_type, :value => @contacts.contact_type %>
                          <% end %>
                        </div>
                      </div>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<% content_for(:head) do -%>
    <%= javascript_include_tag 'contacts' %>
    <%= javascript_include_tag 'form_changed' %>
    <%= stylesheet_link_tag 'profile/contacts' %>
    <%= stylesheet_link_tag 'profile/profile' %>
    <style>
        div.button_container, div.button_container a {
            background-color: <%= profile_primary_background_color %>;
            color: <%= profile_primary_text_color %>;
        }

        .button_container {
            border-color: <%= profile_primary_background_color %>;
        }

        .content_box h1.boxed {
            color: <%= profile_primary_text_color %>;
            background-color: <%= profile_primary_background_color %>;
        }

        .content_box h2 {
            background-color: <%= profile_secondary_background_color %> !important;
            color: <%= profile_secondary_text_color %> !important;
        }

         p.error_box{
             font-size: 80%;
             line-height: 130%;
         }

    </style>
<% end %>
<div class="edit-contact-container">
  <% if flash[:error] -%>
      <p class="error_box" style="margin-bottom: 8px;">
        <% flash[:error].each do |msg| %>
            <%= msg %>
            <br/>
        <% end %>
      </p>
  <% end %>
  <%= form_for(@contacts, url: update_contact_path) do |f| %>

      <%= render :partial => 'contacts', :object => @contacts, :locals => {:f => f} %>

      <div class="button_container" id="contacts_button_container">
        <%= submit_tag(update_button_label, :id => 'contact_yui_button') %>
        <%= link_to "Back", contacts_url %>
      </div>

  <% end %>
</div>

app/views/contacts/index.html.erb
<% content_for(:head) do -%>
    <%= javascript_include_tag 'profile' %>
    <%= javascript_include_tag 'contacts' %>
    <%= stylesheet_link_tag 'profile/contacts' %>
    <%= stylesheet_link_tag 'profile/profile' %>
    <style>
        div.button_container, div.button_container a {
            background-color: <%= profile_primary_background_color %>;
            color: <%= profile_primary_text_color %>;
        }

        .button_container {
            margin: 10px;
            float: right;
            border-color: <%= profile_primary_background_color %>;
        }

        .content_box h1.boxed {
            color: <%= profile_primary_text_color %>;
            background-color: <%= profile_primary_background_color %>;
        }

        .content_box h2 {
            background-color: <%= profile_secondary_background_color %> !important;
            color: <%= profile_secondary_text_color %> !important;
        }

        .title-row {
            color: <%= profile_primary_text_color %>;
            background-color: <%= profile_primary_background_color %>;
        }

        p.notice_box {
            font-size: 80%;
            line-height: 130%;
        }

    </style>
<% end %>

<div id="header_container">
  <h1><%= contact_index_header %></h1>
</div>

<% if flash[:save_message] -%>
    <p class="notice_box" style="margin-left: 15px;">
      <%= flash[:save_message] %>
    </p>
<% end %>

    <table class="display" id="contacts">
      <thead>
      <tr class="title-row">
        <th>Name</th>
        <th>Email</th>
        <th>Telephone</th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.name %></td>
            <td><%= contact.email_address %></td>
            <td><%= formatted_phone(contact.telephone) %></td>
            <td class ="td_center"><%= link_to "View", contact_path(contact.id) %></td>
            <td class ="td_center">
              <%= link_to "Delete",
                      delete_contact_path(contact.id),
                      data: {
                        confirm: "Are you sure you want to delete this contact?"
                      },
                      method: 'post' %></td>
          </tr>
      <% end %>
      </tbody>

    </table>

<% if display_add_contact_button?%>
    <div class="button_container" id="add_button_container">
      <%#= button_tag("Add New Contact", :url => contacts_new_url, :id => 'link_button') %>
      <%= button_to "Add New Contact", contacts_new_url, :id => "add_contact_yui_button",
                    :method => :get %>
    </div>
<% end %>

app/views/contacts/new.html.erb
<% content_for(:head) do -%>

    <%= javascript_include_tag 'profile' %>
    <%= javascript_include_tag 'contacts' %>
    <%= stylesheet_link_tag 'profile/contacts' %>
    <%= stylesheet_link_tag 'profile/profile' %>
    <style>
        div.button_container, div.button_container a {
            background-color: <%= profile_primary_background_color %>;
            color: <%= profile_primary_text_color %>;
        }

        .button_container {
            border-color: <%= profile_primary_background_color %>;
        }

        .content_box h1.boxed {
            color: <%= profile_primary_text_color %>;
            background-color: <%= profile_primary_background_color %>;
        }

        .content_box h2 {
            background-color: <%= profile_secondary_background_color %> !important;
            color: <%= profile_secondary_text_color %> !important;
        }

        p.error_box {
            font-size: 80%;
            line-height: 130%;
        }
    </style>
<% end %>
<div class="edit-contact-container">
  <% if flash[:error] -%>
      <p class="error_box" style="margin-bottom: 8px;">
        <% flash[:error].each do |msg| %>
            <%= msg %>
            <br/>
        <% end %>
      </p>
  <% end %>
  <%= form_for(@contacts, url: create_contact_path, action: "create") do |f| %>

      <% if @errors -%>
          <p class="error_box" style="margin-bottom: 8px;">
            <%= @errors.join('<br/>').html_safe %>
          </p>
      <% end -%>
      <% if @notice -%>
          <p class="notice_box" style="margin-bottom: 8px">
            <%= @notice %>
          </p>
      <% end -%>

      <%= render :partial => 'contacts', :object => @contacts, :locals => {:f => f} %>

      <div class="button_container" id="contacts_button_container">
        <%= submit_tag(create_button_label, :id => 'new_contact_yui_button') %>
        <%= link_to "Back", contacts_url %>
      </div>
  <% end %>
</div>