config/routes.rb
ProfilesDialog::Application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    mount HudsonBase::Engine, :at  => 'hudson_base', :as => 'hudson_base'

    match 'forgot_my_password' => 'user#forgot_my_password', as: :forgot_password, via: :all
    match 'locations' => 'locations#index', as: :locations, via: :all
    match 'login' => 'user#login', as: :login, via: :all
    match 'logout' => 'user#logout', as: :logout, via: :all
    match 'new' => 'profile#new', as: :new, via: :all
    match 'points' => 'points#index', as: :points, via: :all
    # match 'points_clone' => 'points#index_clone', as: :points_clone, via: :all
    match 'contacts' => 'contacts#index', as: :contacts, via: :get


    match 'reservations' => 'reservations#index', as: :reservations, via: :all
    get 'reservation' => 'reservations#reservation', as: :reservation
    match 'reservation/grid_info' => 'reservations#grid_info', as: :grid_info, via: :all
    get 'reservation/res_edit_address' => 'reservations#res_edit_address',
         as: :get_res_edit_address

    match 'profile' => 'profile#profile', as: :profile, via: :all
    get 'address_lookup' => 'locations#address_lookup'
    get 'location_info' => 'locations#location_info'
    get 'address_from_lookup' => 'locations#address_from_lookup'
    get "contacts/new" => 'contacts#new'
    get 'contacts/:id/edit' => 'contacts#edit', as: :contact
    post 'contacts/:id/delete' => 'contacts#delete', as: :delete_contact
    post 'contacts/:id' => 'contacts#save' , as: :update_contact
    post 'contacts' => 'contacts#create' , as: :create_contact

    post 'pud' => 'locations#pud'
    match ':action' => 'profile#index', via: :all
    match ':controller/:action' => '#index', via: :all

  end
end

app/views/layouts/_error_box.html.erb
<div class="info-box-container">
  <p>
    <%= token('PROFILE_EDIT_HEADER') %>
  </p>
  <% if @errors -%>
  <p class="error_box" style="margin-bottom: 8px;">
    <%= @errors.join('<br/>').html_safe %>
  </p>
  <% end -%>
  <% if @notice -%>
  <p class="notice_box" style="margin-bottom: 8px">
    <%= @notice %>
  </p>
  <% end -%>
</div>

app/views/layouts/_theme_styles.html.erb
<style>
  html, body {
    background-color: <%= profile_site_background_color %>;
    color: <%= profile_site_text_color %>;
  }

  .w3-theme {
    color: <%=primary_text_color%> !important;
    background-color: <%=primary_background_color%> !important;
  }

  .w3-theme-inverse {
    color: <%=primary_background_color%> !important;
    background-color: <%=primary_text_color%> !important;
  }

  .w3-text-theme-border {
    border-color: <%=profile_subsection_text_color%> !important;
  }
  .w3-text-theme-primary {
    color: <%=primary_background_color%> !important;
  }
  .w3-text-theme {
    color: <%= profile_subsection_text_color %> !important;
  }
  .nav-link:hover {
    border-color: <%=primary_text_color%> !important;
  }
  .submit-button, #login_button, #new-profile-submit-button, #forgot_pw_button {
    background-color: <%= profile_site_background_color %> !important;
    color: <%=primary_background_color%> !important;
  }
  .submit-button:hover, #login_button:hover, #new-profile-submit-button:hover, #forgot_pw_button:hover {
    background-color: <%=primary_background_color%> !important;
    color: <%= profile_site_background_color %> !important;
  }
  #please_wait_span {
    color: <%=primary_background_color%> !important;
  }

  /* Zebra striping */
  #transactions tr:nth-of-type(even) {
    background-color: <%= alt_row_color %> !important;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application'  %>
    <%= stylesheet_link_tag 'application' %>

    <!--[if lt IE 9]>
      <script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= render "layouts/theme_styles" %>
    <%= yield :head %>
  </head>
  <%= content_tag :body,
  data: {
      controller: controller_name,
      action: action_name,
      site: current_site_id,
      env: Rails.env,
      urls: {
      'location-info' => location_info_path,
      'pud' => pud_path,
      'address-lookup' => address_lookup_path,
      'address-from-lookup' => address_from_lookup_path,
      'profiles-url' => profile_path
      }
  } do %>
  <!-- Content -->
  <div class="w3-container w3-theme" id="nav-container">
    <ul id="profile-nav">
      <%= tab(tab_label(:message), url_for(:controller => 'profile', :action => 'message'), tab_icon(:message), params[:action] == 'message') if new_profile? %>
      <%= tab(tab_label(:profile), url_for(:controller => 'profile', :action => 'profile'), tab_icon(:profile), ['profile'].include?(params[:action]))%>
      <%#= tab(tab_label(:locations), locations_url, tab_icon(:locations), params[:controller] == 'locations') if locations_enabled? %>
      <%= tab(tab_label(:reservations), reservations_path, tab_icon(:reservations), ['reservations'].include?(params[:controller])) if reservations_enabled? %>
      <%= tab(tab_label(:points), points_url, tab_icon(:points), params[:controller] == 'points') if points_enabled?%>

    </ul>
  </div>
  <%= render "layouts/error_box" %>
  <%= yield :layout %>
  <script>
  if (window.parent && window.parent.profile_window_loaded) {
  window.parent.profile_window_loaded();
  }
  </script>
  <% end %>
</html>

app/views/layouts/application_clone.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application'  %>
    <%= stylesheet_link_tag 'application' %>
    <%= render "layouts/theme_styles" %>
    <%= yield :head %>
  </head>
  <%= content_tag :body,
  data: {
      controller: controller_name,
      action: action_name,
      site: current_site_id,
      env: Rails.env,
      urls: {
      'location-info' => location_info_path,
      'pud' => pud_path,
      'address-lookup' => address_lookup_path,
      'address-from-lookup' => address_from_lookup_path,
      'profiles-url' => profile_path
      }
  } do %>
  <!-- Content -->
  <div class="w3-container w3-theme" id="nav-container">
    <ul id="profile-nav">
      <%= tab(tab_label(:message), url_for(:controller => 'profile', :action => 'message'), tab_icon(:message), params[:action] == 'message') if !new_profile? %>
      <%= tab(tab_label(:reservations), reservations_path, tab_icon(:reservations), ['reservations'].include?(params[:controller])) if reservations_enabled? %>
      <%= tab(tab_label(:profile), url_for(:controller => 'profile', :action => 'profile'), tab_icon(:profile), ['profile'].include?(params[:action]))%>
      <%= tab(tab_label(:locations), locations_url, tab_icon(:locations), params[:controller] == 'locations') if locations_enabled? %>
      <%= tab(tab_label(:points), points_url, tab_icon(:points), params[:controller] == 'points') if points_enabled?%>
      <%= tab(tab_label(:points), points_clone_url, tab_icon(:points), params[:controller] == 'points') if points_enabled?%>
      <%= tab(tab_label(:contacts), contacts_url, tab_icon(:contacts), params[:controller] == 'contacts') if contacts_enabled? %>
    </ul>
  </div>
  <%= render "layouts/error_box" %>
  <%= yield :layout %>
  <script>
  if (window.parent && window.parent.profile_window_loaded) {
  window.parent.profile_window_loaded();
  }
  </script>
  <% end %>
</html>

app/views/layouts/application_guest.html.erb
<!DOCTYPE html>
<!--[if IE 8 ]> <html class="lt-ie10 ie8" lang="en"> <![endif]-->
<!--[if IE 9]><html class="lt-ie10" lang="en"> <![endif]-->
<!--[if (gt IE 8)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet" type="text/css">
    <link href='//fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= site_stylesheet %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>

    <!--[if lt IE 9]>
      <script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
      <%= javascript_include_tag 'respond/respond' %>
    <![endif]-->

    <style>
      <%= current_theme_css %>
      <%= themed_button %>
      <%= darker_primary_css %>
    </style>

    <%= render partial: 'shared/analytics' unless controller_name == 'profile' %>
    <%= yield :head %>
  </head>

  <%= content_tag :body,
          class: "hudson-app #{site_body_class}",
          data: {
            controller: controller_name,
            action: action_name,
            site: current_site_id,
            env: Rails.env,
            compat_message: ie_compatible_view_msg,
            height_padding: @height_padding,
            urls: {
              apply_coupon: apply_coupon_path,
              attraction_info: attraction_update_info_path,
              block_check: block_check_path,
              cruise_locations: cruise_arriving_locations_path,
              cruise_arr_hotel_dests: cruise_arr_hotel_dests_path,
              cruise_arr_hotel_hotels: cruise_arr_hotel_hotels_path,
              cruise_booking_container: cruise_booking_container_path,
              cruise_dep_hotel_dests: cruise_dep_hotel_dests_path,
              cruise_departing_locations: cruise_dep_locations_path,
              flight_cities: flight_cities_path,
              locations: locations_path,
              login_modal: login_modal_path,
              login_window: login_window_path,
              reload_profile: reload_profile_path,
              remove_coupon: remove_coupon_path,
              svc_extras: svc_extras_path,
              svc_update: services_update_path
            }
          } do %>
    <%= yield %>
  <% end %>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_include_tag 'application'  %>
    <%= stylesheet_link_tag 'application' %>
    <style>
    html, body {
    background-color: <%= profile_site_background_color %>;
    color: <%= profile_site_text_color %>;
    }
    <%= render "layouts/theme_styles" %>
    <%= yield :head %>
    </style>
  </head>
  <body>
    <!-- Content -->
    <div class="w3-margin-bottom" id="content-window">
      <%= yield :layout %>
    </div>
    <script>
    if (window.parent && window.parent.profile_window_loaded) {
    window.parent.profile_window_loaded();
    }
    </script>
  </body>
</html>